dist: bionic
os: linux
language: c++

before_install:
  - bash scripts/install.sh
  - sudo apt install gcc-8 g++-8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j8
